package com.xiaobo.demo.pojo;

import com.xiaobo.demo.util.EntityToString;
import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table email_code
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class EmailCode implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_code.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_code.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   ��֤��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   ����ʱ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_code.create_at
     *
     * @mbg.generated
     */
    private String createAt;

    /**
     * Database Column Remarks:
     *   ����ʱ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_code.update_at
     *
     * @mbg.generated
     */
    private String updateAt;

    /**
     * Database Column Remarks:
     *   �������·����ʼ�����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_code.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_code.id
     *
     * @return the value of email_code.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_code.id
     *
     * @param id the value for email_code.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_code.email
     *
     * @return the value of email_code.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_code.email
     *
     * @param email the value for email_code.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_code.code
     *
     * @return the value of email_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_code.code
     *
     * @param code the value for email_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_code.create_at
     *
     * @return the value of email_code.create_at
     *
     * @mbg.generated
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_code.create_at
     *
     * @param createAt the value for email_code.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_code.update_at
     *
     * @return the value of email_code.update_at
     *
     * @mbg.generated
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_code.update_at
     *
     * @param updateAt the value for email_code.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_code.number
     *
     * @return the value of email_code.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_code.number
     *
     * @param number the value for email_code.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
    @Override
    public String toString(){
        return EntityToString.getString(this,this.getClass( ));
    }
}