package com.xiaobo.demo.dao;

import com.xiaobo.demo.pojo.PhoneCode;

public interface PhoneCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_code
     *
     * @mbg.generated
     */
    int insert(PhoneCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_code
     *
     * @mbg.generated
     */
    int insertSelective(PhoneCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_code
     *
     * @mbg.generated
     */
    PhoneCode selectByPrimaryKey(Integer id);

    PhoneCode selectByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PhoneCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PhoneCode record);
}