package com.xiaobo.demo.pojo;

import com.xiaobo.demo.util.EntityToString;
import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table excellent_student
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class ExcellentStudent implements Serializable {
    public static final Integer EXCELLENT_STUDENT_STATUS_STUDY = 1;
    public static final Integer EXCELLENT_STUDENT_STATUS_GRADUATED = 2;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.img
     *
     * @mbg.generated
     */



    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.salary
     *
     * @mbg.generated
     */
    private Integer salary;

    private Integer status;

    private Integer professionName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.create_at
     *
     * @mbg.generated
     */
    private Long createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excellent_student.update_at
     *
     * @mbg.generated
     */
    private Long updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.id
     *
     * @return the value of excellent_student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.id
     *
     * @param id the value for excellent_student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.img
     *
     * @return the value of excellent_student.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.img
     *
     * @param img the value for excellent_student.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.position
     *
     * @return the value of excellent_student.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.position
     *
     * @param position the value for excellent_student.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.name
     *
     * @return the value of excellent_student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.name
     *
     * @param name the value for excellent_student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.description
     *
     * @return the value of excellent_student.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.description
     *
     * @param description the value for excellent_student.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.salary
     *
     * @return the value of excellent_student.salary
     *
     * @mbg.generated
     */
    public Integer getSalary() {
        return salary;
    }

    public Integer getStatus() {
        return status;
    }

    public Integer getProfessionName() {
        return professionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.salary
     *
     * @param salary the value for excellent_student.salary
     *
     * @mbg.generated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }
    public void setStatus(Integer status) {
        this.status = status;
    }
    public void setProfessionName(Integer professionName) {
        this.professionName = professionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.create_at
     *
     * @return the value of excellent_student.create_at
     *
     * @mbg.generated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.create_at
     *
     * @param createAt the value for excellent_student.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excellent_student.update_at
     *
     * @return the value of excellent_student.update_at
     *
     * @mbg.generated
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excellent_student.update_at
     *
     * @param updateAt the value for excellent_student.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }
    @Override
    public String toString(){
        return EntityToString.getString(this,this.getClass( ));
    }
}