package com.xiaobo.demo.dao;

import com.xiaobo.demo.pojo.Profession;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProfessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated
     */
    Profession selectByPrimaryKey(Integer id);
    List<Profession> selectByDevelopmentDirection(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Profession record);
}