package com.xiaobo.demo.pojo;

import com.xiaobo.demo.util.EntityToString;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table phone_code
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class PhoneCode implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_code.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   �ֻ�����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_code.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   ������֤��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   �����ѷ��Ͷ�����֤������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_code.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * Database Column Remarks:
     *   ����ʱ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_code.create_at
     *
     * @mbg.generated
     */
    private Long createAt;

    /**
     * Database Column Remarks:
     *   ����ʱ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_code.update_at
     *
     * @mbg.generated
     */
    private Long updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_code.id
     *
     * @return the value of phone_code.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_code.id
     *
     * @param id the value for phone_code.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_code.phone
     *
     * @return the value of phone_code.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_code.phone
     *
     * @param phone the value for phone_code.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_code.code
     *
     * @return the value of phone_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_code.code
     *
     * @param code the value for phone_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_code.number
     *
     * @return the value of phone_code.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_code.number
     *
     * @param number the value for phone_code.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_code.create_at
     *
     * @return the value of phone_code.create_at
     *
     * @mbg.generated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_code.create_at
     *
     * @param createAt the value for phone_code.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_code.update_at
     *
     * @return the value of phone_code.update_at
     *
     * @mbg.generated
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_code.update_at
     *
     * @param updateAt the value for phone_code.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }
    @Override
    public String toString(){
        return EntityToString.getString(this,this.getClass( ));
    }
}