angular.module('app')
    .constant('professionCount', {
        defaultHttpData: {
            companyId: '',
            companyName: '',
            name: '',
            category: '',
            subCategory: '',
            education: '',
            experience: '',
            startAt: '',
            endAt: '',
            compensation: '',
            status: '',
            page: 1,
            size: 10
        },
        category: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "产品"
        }, {
            type: 1,
            name: "运营"
        }, {
            type: 2,
            name: "技术"
        }, {
            type: 3,
            name: "设计"
        }, {
            type: 4,
            name: "测试"
        }],
        subCategory: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "产品经理 "
        }, {
            type: 1,
            name: "JAVA"
        }, {
            type: 2,
            name: "IOS"
        }, {
            type: 3,
            name: "Android"
        }, {
            type: 4,
            name: "Web前端"
        }, {
            type: 5,
            name: "运维"
        }, {
            type: 6,
            name: "UI设计"
        }, {
            type: 7,
            name: "QA"
        }],
        education: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "大专"
        }, {
            type: 1,
            name: "本科"
        }, {
            type: 2,
            name: "硕士"
        }, {
            type: 3,
            name: "博士"
        }],
        experience: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "应届"
        }, {
            type: 1,
            name: "1~2年"
        }, {
            type: 2,
            name: "3~5年"
        }, {
            type: 3,
            name: "6~9年"
        }, {
            type: 4,
            name: "10年以上"
        }],
        compensation: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "0~8K"
        }, {
            type: 1,
            name: "8~15K"
        }, {
            type: 2,
            name: "16~25K"
        }, {
            type: 3,
            name: "26K以上"
        }],
        status: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "上架"
        }, {
            type: 1,
            name: "下架"
        }],
        recommend: [{
            type: '',
            name: '请选择'
        }, {
            type: 0,
            name: "普通"
        }, {
            type: 1,
            name: "推荐"
        }]
    })
